
package client;

import java.awt.Desktop;
import java.awt.Font;
import java.awt.Graphics2D;
import java.awt.Toolkit;
import java.awt.datatransfer.Clipboard;
import java.awt.datatransfer.DataFlavor;
import java.awt.datatransfer.Transferable;
import java.awt.datatransfer.UnsupportedFlavorException;
import java.awt.image.BufferedImage;

import java.io.File;

import java.io.IOException;

import java.net.URI;
import java.net.URISyntaxException;

import java.text.SimpleDateFormat;

import java.util.Date;

import javax.imageio.ImageIO;

import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Carlos
 */
public class VentanaPrincipalJFrame extends javax.swing.JFrame {
    File file = new File(".");
    private String nl = System.getProperty("line.separator");
    private Imagenes imagenes = new Imagenes();
    private JLabel[][] jLabelMatriz = new JLabel[7][7];
    private Matriz matriz = null;
    private int ancho = 0;
    private int alto = 0;

    /** Creates new form VentanaPrincipalJFrame */
    public VentanaPrincipalJFrame() {
        try {
            initComponents();
            jbInit();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    private void jbInit() throws Exception {
        
        for(int x=0;x<7;x++){
            for(int y=0;y<7;y++){
                jLabelMatriz[x][y]=new JLabel();
                jLabelMatriz[x][y].setText(""+ x + ":" + y);
                jLabelMatriz[x][y].setHorizontalAlignment(jLabelMatriz[x][y].CENTER);
                jLabelMatriz[x][y].setOpaque(true);
                jLabelMatriz[x][y].setFont(new Font("Arial", 1, 16));
                jPanel1.add(jLabelMatriz[x][y], null);
            }
        }
        matriz = new Matriz(jLabelMatriz);

        ancho = jPanel1.getSize().width;
        alto = jPanel1.getSize().height;
        if(ancho > alto) {
          this.matriz.setAnchoXaltoY(alto/8);
        }else{
          this.matriz.setAnchoXaltoY(ancho/8);  
        }
        
        matriz.setS(this.jCheckBox2.isSelected(),
                    this.jCheckBox3.isSelected(),
                    this.jCheckBox5.isSelected(),
                    this.jCheckBox1.isSelected());
        this.setIconImage(imagenes.getImage());
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {//GEN-BEGIN:initComponents

        jToolBar1 = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        jCheckBox1 = new javax.swing.JCheckBox();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        jCheckBox3 = new javax.swing.JCheckBox();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        jCheckBox2 = new javax.swing.JCheckBox();
        jSeparator5 = new javax.swing.JToolBar.Separator();
        jCheckBox5 = new javax.swing.JCheckBox();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Generador de contenidos");
        setMinimumSize(new java.awt.Dimension(500, 400));
        getContentPane().setLayout(new java.awt.BorderLayout());

        jToolBar1.setRollover(true);

        jButton1.setText("Nuevo");
        jButton1.setToolTipText("Genera un nuevo contenido");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton1);

        jButton2.setText("Guardar");
        jButton2.setToolTipText("Pone el ejercicio en el porta papeles y guarda un archivo con la solución");
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton2);

        jButton3.setText("Configurar");
        jButton3.setToolTipText("Permite elegir colores y tipo de letras");
        jButton3.setFocusable(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton3);
        jToolBar1.add(jSeparator2);

        jCheckBox1.setSelected(true);
        jCheckBox1.setText("Op");
        jCheckBox1.setToolTipText("Encontrar la igualdad, oculta los resultados");
        jCheckBox1.setFocusable(false);
        jCheckBox1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jCheckBox1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jCheckBox1);
        jToolBar1.add(jSeparator3);

        jCheckBox3.setSelected(true);
        jCheckBox3.setText("xy");
        jCheckBox3.setToolTipText("Incluir variables x e y");
        jCheckBox3.setFocusable(false);
        jCheckBox3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jCheckBox3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jCheckBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox3ActionPerformed(evt);
            }
        });
        jToolBar1.add(jCheckBox3);
        jToolBar1.add(jSeparator4);

        jCheckBox2.setSelected(true);
        jCheckBox2.setText("Div Mul");
        jCheckBox2.setToolTipText("Incluir división y multiplicación");
        jCheckBox2.setFocusable(false);
        jCheckBox2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jCheckBox2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });
        jToolBar1.add(jCheckBox2);
        jToolBar1.add(jSeparator5);

        jCheckBox5.setSelected(true);
        jCheckBox5.setText("Ico");
        jCheckBox5.setToolTipText("Usar iconos");
        jCheckBox5.setFocusable(false);
        jCheckBox5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jCheckBox5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jCheckBox5);
        jToolBar1.add(jSeparator1);

        jButton4.setText("Blog");
        jButton4.setToolTipText("https://carlosprivitera.blogspot.com.ar/");
        jButton4.setFocusable(false);
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton4);

        jButton5.setText("GitHub");
        jButton5.setToolTipText("https://github.com/carlosprivitera");
        jButton5.setFocusable(false);
        jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton5);

        getContentPane().add(jToolBar1, java.awt.BorderLayout.NORTH);

        jPanel1.setBackground(new java.awt.Color(255, 102, 0));
        jPanel1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                jPanel1ComponentResized(evt);
            }
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jPanel1ComponentShown(evt);
            }
        });
        jPanel1.addHierarchyBoundsListener(new java.awt.event.HierarchyBoundsListener() {
            public void ancestorMoved(java.awt.event.HierarchyEvent evt) {
            }
            public void ancestorResized(java.awt.event.HierarchyEvent evt) {
                jPanel1AncestorResized(evt);
            }
        });
        jPanel1.setLayout(new java.awt.GridLayout(7, 7, 2, 2));
        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jLabel1.setText("https://carlosprivitera.blogspot.com.ar/");
        jLabel1.setToolTipText("https://carlosprivitera.blogspot.com.ar/");
        getContentPane().add(jLabel1, java.awt.BorderLayout.PAGE_END);

        pack();
        setLocationRelativeTo(null);
    }//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.jButton1.setEnabled(false);
        matriz.setS(this.jCheckBox2.isSelected(),
                    this.jCheckBox3.isSelected(),
                    this.jCheckBox5.isSelected(),
                    this.jCheckBox1.isSelected());
        this.jLabel1.setText("x="+matriz.getValorX()+" y=" + matriz.getValorY());
        this.jButton2.setEnabled(true);
        this.jButton1.setEnabled(true);        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jCheckBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox3ActionPerformed
    private BufferedImage imagenPublicar = null;
    private BufferedImage imagenPublicar2 = null;
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jButton2.setEnabled(false);
        imagenPublicar = new BufferedImage(jPanel1.getWidth(), jPanel1.getHeight(), BufferedImage.TYPE_INT_RGB);
        imagenPublicar2 = new BufferedImage(getWidth(), getHeight(), BufferedImage.TYPE_INT_RGB);
        Graphics2D g = (Graphics2D)imagenPublicar.getGraphics();
        Graphics2D g2 = (Graphics2D)imagenPublicar2.getGraphics();
        paint(g2);
        try {
           SimpleDateFormat formateador = new SimpleDateFormat("dd-MM-yyyy HH_mm_ss");
           Date d = new Date(); 
           ImageIO.write(imagenPublicar2, "png", new File(formateador.format(d) + "Solucion.png"));
          // matriz.borrarParaPublicar(jCheckBox1.isSelected(),jCheckBox3.isSelected()); 
           jPanel1.paint(g); 
           ImageIO.write(imagenPublicar, "png", new File(formateador.format(d) + "Resolver.png"));
        } catch (IOException es) {
           String error = es.getMessage();
           JOptionPane.showMessageDialog(null, "Error de archivo: " + error);
        } catch (Exception es) {
            String error = es.getMessage();
            JOptionPane.showMessageDialog(null, "Error genérico de archivo: " + error);
        }    
        try {
          Clipboard cb = Toolkit.getDefaultToolkit().getSystemClipboard();
          Transferable ponerEnPP = new Transferable(){
                        @Override
                        public Object getTransferData(DataFlavor flavor)
                                        throws UnsupportedFlavorException, IOException {
                                if (isDataFlavorSupported(flavor)) {
                                        return imagenPublicar;
                                }                      
                          throw new UnsupportedFlavorException(flavor);
                        }
                        @Override
                        public DataFlavor[] getTransferDataFlavors() {
                                // TODO Auto-generated method stub
                                return new DataFlavor[] { DataFlavor.imageFlavor };
                        }
                        @Override
                        public boolean isDataFlavorSupported(DataFlavor flavor) {
                                // TODO Auto-generated method stub
                                return DataFlavor.imageFlavor.equals(flavor);
                        }               
          };
          cb.setContents(ponerEnPP, null);
          } catch (Exception es) {
              String error = es.getMessage();
              JOptionPane.showMessageDialog(null, "Error genérico de portapapeles: " + error);
          } 
        try {
            JOptionPane.showMessageDialog(this, 
                "Se ha guardado en el portapapeles una imagen para publicar en redes sociales"+
                nl+
                "Se han guardado dos archivo en: " + file.getCanonicalPath()+
                nl+
                "Un archivo con la solución y otro con el desafio a publicar en redes sociales");
        } catch (IOException f) {
        }
    }//GEN-LAST:event_jButton2ActionPerformed
    private Configurar configurar = new Configurar();
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        configurar.setLocationRelativeTo(null);
        configurar.setDefaultCloseOperation(configurar.HIDE_ON_CLOSE);
        
        configurar.jPanel1.setBackground(this.jPanel1.getBackground());
        configurar.jLabel1.setBackground(this.jLabelMatriz[0][0].getBackground());
        configurar.jLabel1.setFont(this.jLabelMatriz[0][0].getFont());
        configurar.jLabel1.setForeground(this.jLabelMatriz[0][0].getForeground());
        configurar.iniciarValores();
        configurar.setVisible(true);
        if(configurar.getAplicar()==1){
            this.jPanel1.setBackground(configurar.jPanel1.getBackground());
            for(int x=0;x<7;x++){
                for(int y=0;y<7;y++){
                    jLabelMatriz[x][y].setBackground(configurar.jLabel1.getBackground()); //=new JLabel();
                    jLabelMatriz[x][y].setFont(configurar.jLabel1.getFont()); //setText(""+ x + "" + y);
                    jLabelMatriz[x][y].setForeground(configurar.jLabel1.getForeground()); //setHorizontalAlignment(jButton1[x][y].CENTER);
                }
            }
            
        }
        configurar.setAplicar(0);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        try {
            URI uri = new URI(jButton4.getToolTipText());
            Desktop.getDesktop().browse(uri);
        }catch (URISyntaxException ex) {
        }catch(IOException ex){
        }catch(Exception ex){     
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        try {
            URI uri = new URI(jButton5.getToolTipText());
            Desktop.getDesktop().browse(uri);
        }catch (URISyntaxException ex) {
        }catch(IOException ex){
        }catch(Exception ex){     
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jPanel1ComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel1ComponentResized
        // TODO add your handling code here:
        ancho = jPanel1.getSize().width;
        alto = jPanel1.getSize().height;
        if(ancho > alto) {
          this.matriz.setAnchoXaltoY(alto/8);
        }else{
          this.matriz.setAnchoXaltoY(ancho/8);  
        }        
    }//GEN-LAST:event_jPanel1ComponentResized

    private void jPanel1ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel1ComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1ComponentShown

    private void jPanel1AncestorResized(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_jPanel1AncestorResized
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1AncestorResized

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipalJFrame.class.getName()).log(java.util.logging.Level.SEVERE,
                                                                                           null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipalJFrame.class.getName()).log(java.util.logging.Level.SEVERE,
                                                                                           null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipalJFrame.class.getName()).log(java.util.logging.Level.SEVERE,
                                                                                           null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipalJFrame.class.getName()).log(java.util.logging.Level.SEVERE,
                                                                                           null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipalJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JToolBar.Separator jSeparator5;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
    
}
